services:
  app:
    environment:
      - DB_HOST=54.78.92.196
      - DB_NAME=fastapi_2
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db
  db:
    image: postgres:13-alpine
      environment:
        - POSTGRES_DB=fastapi_2
        - POSTGRES_USER=vinhle
        - POSTGRES_PASSWORD=password
      ports:
        - "5432:5432"